-- 关账竞争门：每次关账尝试一行；active_token 仅在 PENDING 时等于结算日，
-- 唯一约束保证同一结算日至多一个进行中的关账意图（多 NULL 在 PG/H2 均不冲突）。
CREATE TABLE IF NOT EXISTS settlement_day_gate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT NOT NULL DEFAULT 0,
    settlement_date DATE NOT NULL,
    generation      INTEGER NOT NULL,
    state           VARCHAR(16) NOT NULL CHECK (state IN ('PENDING','SUPERSEDED','CLOSED','CANCELLED')),
    active_token    VARCHAR(10) UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_day_gate_date ON settlement_day_gate(settlement_date, generation);
